### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Eweeen** [Eweeen/nasa-vue#1]
Liste des astres :
  - [x] Une page listant l'ensemble des astres
  - [x] Filtres (si c'est une planète, le fait d'avoir des lunes)

Page de l'astre :
  - [x] Ensemble des infomations liées à l'astre
  - [x] Si l'astre est une planète, possédant des lunes, accès rapide vers ses lunes

Page du système solaire :
  - [x] Repésentation graphique des astres de type planète basé sur la distance de l'astre au soleil

Page des favoris :
  - [x] Spécifier des astres en tant que favoris
  - [x] Astre en favori => notification
  - [x] Afficher les favoris
